$kind: http-request
name: Create Inventory
method: POST
url: '{{baseUrl}}/inventory'
order: 1000
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "productId": "{{productId}}",
      "quantity": 10,
      "unit": "kg",
      "preferredMarket": "Charanchi"
    }
